### ISSUE TITLE
dns should only be allowed for the root user

### ISSUE THREAD

**Issue by tripolar** [skullone/android_firewall#1]
on cm9 the root user is used to do the dns lookup, therefore 53/udp shouldn't be allowed for every user.

**Comment by tripolar** [comment]
this would fix it

diff --git a/src/com/jtschohl/androidfirewall/Api.java b/src/com/jtschohl/androidfirewall/Api.java
index 4620ed6..e5a87ea 100644
--- a/src/com/jtschohl/androidfirewall/Api.java
+++ b/src/com/jtschohl/androidfirewall/Api.java
@@ -213,7 +213,7 @@ public final class Api {
                                "$IPTABLES -F droidwall-3g || exit 8\n" +
                                "$IPTABLES -F droidwall-wifi || exit 9\n" +
                                "$IPTABLES -F droidwall-reject || exit 10\n" +
-                               "$IPTABLES -A droidwall -p udp --dport 53 -j RETURN || exit 11\n" +
-                               "$IPTABLES -A droidwall -m owner --uid-owner 0 -p udp --dport 53 -j RETURN || exit 11\n" +
                      "");
                      // Check if logging is enabled
                      if (logenabled) {

**Comment by skullone** [comment]
This fix has been added in version 1.0.2
