### ISSUE TITLE
No rules for 2G blocking

### ISSUE THREAD

**Issue by manjorno** [skullone/android_firewall#15]
The application works when WCDMA (3G) network mode is selected but doesn't block the connections when GSM (2G) mode is selected.

**Comment by skullone** [comment]
Please send me the output from terminal emulator from this command when you are connected to 2G mode:

busybox route

**Comment by manjorno** [comment]
I think the problem was in my phone, i updated my wifi modules and flushed the rules and the problem got fixed. Now the app works as expected.
My phone is SE Xperia mini ISC 4.0.4 Kernel version 2.6.32.9
the mobile data interface there is rmnet0 for both EDGE and HSDPA.

<pre>
app_73@android:/ $ busybox route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.182.184.14   *               255.255.255.255 UH    0      0        0 rmnet0
10.0.0.0        *               255.0.0.0       U     0      0        0 rmnet0
default         10.182.184.14   0.0.0.0         UG    0      0        0 rmnet0
app_73@android:/ $
</pre>

Sorry for the trouble.

**Comment by skullone** [comment]
No worries.  Glad everything works.
