### ISSUE TITLE
help link is not working

### ISSUE THREAD

**Issue by norbertc** [skullone/android_firewall#2]
The help link for the external script dialog is not available.

**Comment by skullone** [comment]
Are you talking about the hyperlink for github?

**Comment by norbertc** [comment]
no. sorry i don't mean external script but rather custom script. it's the help link on the custom script entry dialog.

**Comment by skullone** [comment]
I will correct this in the next version

**Comment by skullone** [comment]
This has been corrected.  It will be in the next update.
