### ISSUE TITLE
Choose interfaces

### ISSUE THREAD

**Issue by Superluminar** [skullone/android_firewall#28]
Hi there,

I'm using bluetooth-teathering to teather my Wifi or 4G connection from my mobile phone to my tablet.
On my tablet, this bypasses any firewall-rules, because a new interface is created, called "bnep0". ("bnep0" is a PAN Interface for bluetooth)

It would be nice to have an option to choose, on which interfaces the rules are applied. For example, if you block an application for VPN, it is also blocked for bnep0.

**Comment by skullone** [comment]
Please e-mail me directly so I can have you test a new build for me with
the bnep0 interface added.

Thanks!

-Jason

**Comment by Superluminar** [comment]
Hi Jason,

thank you for your response!

So what do I have to do?

Yours sincerely,
Dennis

Am 06.05.2013 14:45, schrieb Jason Tschohl:

> Please e-mail me directly so I can have you test a new build for me with
> the bnep0 interface added.
> 
> Thanks!
> 
> -Jason
> 
> On Sat, May 4, 2013 at 4:59 AM, Superluminar

**Comment by skullone** [comment]
e-mail me directly through the link on the Play Store.  I'll send you the
URL for the test version.  :)

-Jason

**Comment by skullone** [comment]
This was corrected in version 2.2.2.
