### ISSUE TITLE
the firewall some times is automatically disabled un a motorola razrxt910

### ISSUE THREAD

**Issue by eltio2k** [skullone/android_firewall#29]
I have checked only whantsap has enabled to connect in a 3g net, and i set that all the others applications to connect only through wifi, when I see the programs that was consumed data today I can see google+ and facebook 
I have a limit by day and when it is close to te 40% it disconnect the 3g, after that I go to the android firewall and press the button to run the rules again... after that some times stop the 3g use some times not, but always after a wile it stop working and let the Internet run free. what you recommend me to do to help you to find which is the the problem?

**Comment by skullone** [comment]
Hello!

I need a logcat after you apply the rules and from when you notice the
issue.  You can use CatLog or aLogcat from the Play Store to send the
logcat to me.

I also need the output from the following commands in Terminal Emulator:

su
iptables -L

Thanks!

-Jason

**Comment by eltio2k** [comment]
You need that I turn off the firewall. Start the logcat and turn on the firewall. And send all the log that it return? 
But I don't know when the firewall start to fail. After a wile I enter to the system tool that you the data consumption by program and i can see a lot of programs and should be only the whatsapp. I attach an screenshot 
But I don't know when it start to fail. 
I'm using watch dog and I set a limit by day when the daily quota is exceed by 40% it disconnect Internet and I realice that the firewall has failing, I enter to the firewall and re apply the rules. 

## This is the result of the iptables - L command

app_251@umts_spyder:/ $ su
root@umts_spyder:/ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination  
           all  --  anywhere             anywhere             ! quota globalAlert: 2097152 bytes
ACCEPT     all  --  anywhere             anywhere  
           all  --  anywhere             anywhere             owner socket exists

Chain FORWARD (policy DROP)
target     prot opt source               destination        

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination  
droidwall  all  --  anywhere             anywhere  
           all  --  anywhere             anywhere             ! quota globalAlert: 2097152 bytes
ACCEPT     all  --  anywhere             anywhere  
           all  --  anywhere             anywhere             owner socket exists

Chain costly_shared (0 references)
target     prot opt source               destination  
penalty_box  all  --  anywhere             anywhere  
           all  --  anywhere             anywhere             owner socket exists
ACCEPT     all  --  anywhere             anywhere           

Chain droidwall (1 references)
target     prot opt source               destination  
FIX ME! implement getprotobynumber() bionic/libc/bionic/stubs.c:456
RETURN     udp  --  anywhere             anywhere             owner UID match root udp dpt:domain
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-3g  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-wifi  all  --  anywhere             anywhere  
droidwall-vpn  all  --  anywhere             anywhere  
droidwall-vpn  all  --  anywhere             anywhere  
droidwall-vpn  all  --  anywhere             anywhere  
droidwall-vpn  all  --  anywhere             anywhere       

Chain droidwall-3g (17 references)
target     prot opt source               destination  
RETURN     all  --  anywhere             anywhere             owner UID match nobody
RETURN     all  --  anywhere             anywhere             owner UID match app_121
droidwall-reject  all  --  anywhere             anywhere    

Chain droidwall-reject (1 references)
target     prot opt source               destination  
LOG        all  --  anywhere             anywhere             LOG level warning uid prefix "[AndroidFirewall] "
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain droidwall-vpn (4 references)
target     prot opt source               destination        

Chain droidwall-wifi (6 references)
target     prot opt source               destination        

Chain penalty_box (1 references)
target     prot opt source               destination  
root@umts_spyder:/ #

---

Enviado desde mi dispositivo android.

-----Original Message-----

**Comment by eltio2k** [comment]
When I try to run

su iptables -L

It says that don't recognize the - L option

Enviado desde mi dispositivo android.

-----Original Message-----

**Comment by skullone** [comment]
Please type su first and grant terminal emulator root permission.   Then
run iptables -L

**Comment by eltio2k** [comment]
Letme know if this iptables helps, or you need that I active adroid firewall and wait that it start to fail and run the iptables and logcat at the same time.

app_251@umts_spyder:/ $ su
root@umts_spyder:/ # iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination        
           all  --  anywhere             anywhere             ! quota globalAlert: 2097152 bytes
ACCEPT     all  --  anywhere             anywhere          
           all  --  anywhere             anywhere             owner socket exists

Chain FORWARD (policy DROP)
target     prot opt source               destination        

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination        
droidwall  all  --  anywhere             anywhere          
           all  --  anywhere             anywhere             ! quota globalAlert: 2097152 bytes
ACCEPT     all  --  anywhere             anywhere          
           all  --  anywhere             anywhere             owner socket exists

Chain costly_shared (0 references)
target     prot opt source               destination        
penalty_box  all  --  anywhere             anywhere        
           all  --  anywhere             anywhere             owner socket exists
ACCEPT     all  --  anywhere             anywhere          

Chain droidwall (1 references)
target     prot opt source               destination        
FIX ME! implement getprotobynumber() bionic/libc/bionic/stubs.c:456
RETURN     udp  --  anywhere             anywhere             owner UID match root udp dpt:domain
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-3g  all  --  anywhere             anywhere        
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-wifi  all  --  anywhere             anywhere      
droidwall-vpn  all  --  anywhere             anywhere      
droidwall-vpn  all  --  anywhere             anywhere      
droidwall-vpn  all  --  anywhere             anywhere      
droidwall-vpn  all  --  anywhere             anywhere      

Chain droidwall-3g (17 references)
target     prot opt source               destination        
RETURN     all  --  anywhere             anywhere             owner UID match nobody
RETURN     all  --  anywhere             anywhere             owner UID match app_121
droidwall-reject  all  --  anywhere             anywhere    

Chain droidwall-reject (1 references)
target     prot opt source               destination        
LOG        all  --  anywhere             anywhere             LOG level warning uid prefix "[AndroidFirewall] "
REJECT     all  --  anywhere             anywhere             reject-with icmp-port-unreachable

Chain droidwall-vpn (4 references)
target     prot opt source               destination        

Chain droidwall-wifi (6 references)
target     prot opt source               destination        

Chain penalty_box (1 references)
target     prot opt source               destination        
root@umts_spyder:/ #

---

 De: Jason Tschohl notifications@github.com
Para: skullone/android_firewall android_firewall@noreply.github.com 
CC: eltio2k eltio2k-temp@yahoo.com.ar 
Enviado: viernes, 10 de mayo de 2013 9:11
Asunto: Re: [android_firewall] the firewall some times is automatically disabled un a motorola razrxt910 (#29)

Please type su first and grant terminal emulator root permission.   Then 
run iptables -L

**Comment by skullone** [comment]
Can you send me three files?  Please e-mail them directly to me. You can
get my e-mail through the Play Store.

You need to use a file explorer that can get root access.  Like ES File
Explorer

On your phone under this directory:

/data/system/

I need the following files:

packages.xml
packages.list
uiderrors.txt

Thanks!

-Jason

**Comment by skullone** [comment]
Is this still an issue?
