### ISSUE TITLE
Request: Disabling of Widget

### ISSUE THREAD

**Issue by lilott8** [skullone/android_firewall#30]
Here's the setup:

I use android firewall in conjunction with smart app protector to control the medium of which internet is accessed.  So one can only access chrome on wireless and not on the 3/4g radio.  So Android firewall controls the rules and smart app protector keeps the user from changing the rules.

It was an unfortunate discovery that one could disable the firewall through the widget :(.  Could it be possible to allow/disable the use of the widget through the android firewall app.  That way the widget can stay disabled and the smart app protector can keep the user from accessing the rules?

If this doesn't make sense, let me know.  Thanks for an awesome app.

**Comment by skullone** [comment]
I assume you're talking about this app?

https://play.google.com/store/apps/details?id=com.sp.protector.free

**Comment by lilott8** [comment]
Correct

**Comment by skullone** [comment]
Please e-mail me directly.  I have a test build for you.  You can e-mail me
through the Play Store.

**Comment by skullone** [comment]
Fixed in version 2.2.5.  If the app is password protected you cannot disable the firewall using a widget.  You can still change profiles when password protected provided the profiles do not disable the firewall.
