### ISSUE TITLE
APK for download?

### ISSUE THREAD

**Issue by oper8** [skullone/android_firewall#38]
DroidWall has the APK for direct download for those of us without GApps.   Is the Android Firewall APK available for direct download somewhere?  Thanks!

**Comment by skullone** [comment]
https://dl.dropboxusercontent.com/u/27775933/AndroidFirewall2.2.6.apk

Starting with version 2.2.7 I will add the download link to the main page of the AF code in some fashion.

**Comment by oper8** [comment]
Thanks!
