### ISSUE TITLE
Firewall don't block after updating to version 2.2.8

### ISSUE THREAD

**Issue by frank-github** [skullone/android_firewall#39]
after updating to latest version in Google Play firewall isn't working anymore
using black list, but apps block with previous version can now talking to internet :-(
after reinstalling old version all working well, applications are blocked successfully

using Samsung Note II (N7100) with stock rom 4.1.2

**Comment by skullone** [comment]
Please email me directly.

**Comment by frank-github** [comment]
fixed with Version 2.2.9
