### ISSUE TITLE
Build iptables etc. from source

### ISSUE THREAD

**Issue by dalb8** [skullone/android_firewall#4]
There is source code for  these projects in external/ but it needs refreshing as they don't build as they are and the documentation is non-existent.

**Comment by skullone** [comment]
The external items are not meant to compile on their own.  They are integrated into the app.

**Comment by dalb8** [comment]
I don't understand. Where do the binaries in res/raw come from so?

**Comment by skullone** [comment]
They come from external sources.  

https://code.google.com/p/busybox-android/
http://busybox.net/
http://git.busybox.net/busybox/

IPtables is built into Linux to begin with.
http://www.netfilter.org/projects/iptables/index.html

It's all open source.  It all builds within the app.  None of what's used is meant to compile independently.  For example there's no reason to have all of busybox in the app.  It's just not needed.

**Comment by dalb8** [comment]
so if I remove res/raw/\* before building the app should still work?

**Comment by skullone** [comment]
No.  If you remove that information the application will fail to compile because it needs the GREP command from Busybox and needs the $IPTABLES commands.

**Comment by dalb8** [comment]
Could you explain to the layman, why it needs busybox just to search through some text and why iptables is needed if its already in the kernel? Anyway, I still dont understand how "source code" can contain binaries.

**Comment by skullone** [comment]
Many parts of the Linux kernel are left out of the version used in Android for the sake of space.  IPtables and the commands in Busybox are some of them.  Take a stock Android phone, install Terminal Emulator and type ifconfig.  Nothing happens.  Root the phone, install Busybox, and type ifconfig you still get nothing.  However, type busybox ifconfig and it generates results.

**Comment by dalb8** [comment]
OK, but if I have CM10 can I leave res/raw out?

**Comment by skullone** [comment]
No. The app is not designed to use busybox or iptables if it is included with a ROM.  The app is designed to work on any device regardless of ROM or kernel.  Not all ROMs include the needed information.
