### ISSUE TITLE
Wlan networks

### ISSUE THREAD

**Issue by KOLANICH** [skullone/android_firewall#42]
It will be good to have the rules concerning concrete wi-fi networks and vpns and some mechanism to make logic.
For example i have a trusted network A and trusted vpn B.
And i want to make some apps (in particular that ones that don't use encryption) not to have internet access unless (we are connected to A OR we use VPN B)

**Comment by skullone** [comment]
Is this not possible already using Tasker and the profiles in AF?  Tasker
gives you the ability to watch for certain networks.  For example if it is
a "trusted" network that you connect to then Tasker will load your profile
for that network.

**Comment by KOLANICH** [comment]
Thanks, but I don't think it is a good idea to continiusly change iptables rules.
