### ISSUE TITLE
OpenVpn settings

### ISSUE THREAD

**Issue by Mitchoo** [skullone/android_firewall#5]
What are the rules or advised configuration to allow OpenVpn but prevent applications that are blacklisted? Using the official OpenVpn Connect client, connecting to various predefined vpn servers.

**Comment by skullone** [comment]
There is no explicit VPN Rules support in the application.  At some point in the future I may add explicit VPN Rules support to handle that.

However, what you might try doing for the time being is use the import/export rules ability.  When you connect to the VPN simply change to whitelist and load a rules list that only allows the apps you want to access data.

**Comment by Mitchoo** [comment]
Ok, thanks for all the hard work for the community.

P.S.
Since everyone is already paying to use VPN you should definitely 
consider developing a Premium Android Firewall.
And sell the whole thing for a million bucks :-)
http://mobile.nytimes.com/2013/01/01/technology/antivirus-makers-work-on-software-to-catch-malware-more-effectively.xml 

Mitchoo

**Comment by skullone** [comment]
This has been added to version 2.1.4.
