### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by 8948422** [skullone/android_firewall#50]
I used this ftp server https://play.google.com/store/apps/details?id=lutey.FTPServer on my HTC One. Transfer binary data was failed when firewall is on :(

**Comment by AlexSamad** [comment]
Can you explain more. It allowed it through when it shouldn't have or it didn't allow it through ?
Did you have active or passive ftp setup ?

**Comment by 8948422** [comment]
Active or passive is a client mode, not server. I tried both.

**Comment by 8948422** [comment]
White list, all options (wifi, data, lan, input) for FTPServer is allowed

**Comment by skullone** [comment]
It's working for me with the settings you provided.  Please provide screenshots and a logcat of the failure.

**Comment by 8948422** [comment]
Try to download any file from phone

**Comment by skullone** [comment]
I did.  I successfully logged into the server.  Listed all the files.  Then
downloaded a file from the phone.

**Comment by 8948422** [comment]
Big file?

**Comment by skullone** [comment]
Few MB. So you are trying very large files?

**Comment by 8948422** [comment]
![1](https://f.cloud.github.com/assets/5592692/1253342/4b690934-2b62-11e3-83b1-dd9dc8788454.png)

**Comment by 8948422** [comment]
7 181 265 bytes

**Comment by 8948422** [comment]
Sorry, file size is 2 118 722

**Comment by skullone** [comment]
When I get home I will test a larger file.

**Comment by 8948422** [comment]
2 Mb is not a very big file :)

**Comment by 8948422** [comment]
If size less then 1Mb transfering is ok

**Comment by skullone** [comment]
Upon further investigation it appears there is some sort of communication between the server and client that goes through the kernel that signals EOF/successful transfer.

Allowing the kernel in the firewall allows the files to complete.  I don't think even the small files are 100% complete without this.  I transferred a 346.2MB video file between my phone to my laptop via WiFi.

Without kernel allowed only 345.6MB would get through.  I did this 4 times to make sure it wasn't something fluky.
With kernel allowed the full file was transferred.

The not allowed kernel definitely blocks data flow between the server and the client.  You can see this for yourself by enabling the logs.

**Comment by 8948422** [comment]
How to correct it?

**Comment by skullone** [comment]
Allow Kernel in the firewall.  It is in the list.

**Comment by 8948422** [comment]
Allow only LAN?

**Comment by skullone** [comment]
LAN is probably all you need yes.

**Comment by 8948422** [comment]
Thank you. Your work is awesome. Bless you!
