### ISSUE TITLE
Some Synchronisations not blocked on Razr i

### ISSUE THREAD

**Issue by ghost** [skullone/android_firewall#51]
Hello,

my device is a Motorola Razr i with Android 4.1.2, Root and CWM-Recovery. The problem is, that some apps/synchronisations aren't blocked: Firewall is on in whitelist-mode, no apps aren't allowed for Internet. Anyway it is possible, that this synchronisations under my Google-account are funcional: "Browser", "App Data", "GooglePlay Books".

Thanks and sorry for may bad english!

Dear Berns.

**Comment by skullone** [comment]
These are API's that cannot be affected by iptables.
