### ISSUE TITLE
Will support hiding disabled app?

### ISSUE THREAD

**Issue by ghost** [skullone/android_firewall#58]

**Comment by skullone** [comment]
I will look into this.

**Comment by skullone** [comment]
This has been corrected.  When version 2.3.5 is released (no ETA) disabled apps will no longer appear in the app list.

**Comment by p3730r** [comment]
I disable/re-enable apps from time to time. While I appreciate not displaying disabled apps in AF, I'd really love if rules for these app are kept and restored as the respective app is re-enabled. This seems to work during sessions atm, but as soon as the device is rebooted, all rules for disabled apps are lost.

**Comment by skullone** [comment]
In version 2.3.6 i will make it so that showing or not showing disabled
apps is a user setting.

**Comment by p3730r** [comment]
Really nice, thank you!

+donated :)
