### ISSUE TITLE
Logs are empty

### ISSUE THREAD

**Issue by michaelh99** [skullone/android_firewall#60]
I know this was to have been fixed with issue 31 but I'm seeing logs that are empty on my HTC One S (tmo)
I started having this problem with droidwall after the latest update from tmo and thought it might be a dw problem given how long it's been since that app has been updated.
I learned of af today but it has the same issue.
The app appears to be working fine otherwise

**Comment by skullone** [comment]
Please e-mail me directly so I can get more information.

**Comment by michaelh99** [comment]
```
pingJason Tschohl said the following on
  11/26/2013 1:16 PM:
Please e-mail me directly so I can get more
  information.

  On Tue, Nov 26, 2013 at 2:12 PM, michaelh99
  <notifications@github.com>wrote:

  > I know this was to have been fixed with issue 31 but I'm
  seeing logs that

  > are empty on my HTC One S (tmo)

  > I started having this problem with droidwall after the latest
  update from

  > tmo and thought it might be a dw problem given how long it's
  been since

  > that app has been updated.

  > I learned of af today but it has the same issue.

  > The app appears to be working fine otherwise

  >

  > —

  > Reply to this email directly or view it on
  GitHub<https://github.com/skullone/android_firewall/issues/60>

  > .

  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by skullone** [comment]
edited out email addy  E-mail me there

**Comment by skullone** [comment]
This is not an issue with the app.  The latest update from HTC for the One S removed the LOG module from the kernel.  NFLOG is also not present.  A future update from HTC (if there is one) will hopefully correct the devices issues otherwise a custom kernel is needed.
