### ISSUE TITLE
adb over wifi is always blocked

### ISSUE THREAD

**Issue by grebulon** [skullone/android_firewall#65]
I configured my device to connect to adb over wifi using this method:
forum.xda-developers.com/showthread.php?t=1685736
The firewall blocks, even when enabling kernel and root apps.

**Comment by skullone** [comment]
I'll look into it.

**Comment by skullone** [comment]
Try allowing Linux Shell.  That's all I have to do to get ADB over WiFi to function.

**Comment by grebulon** [comment]
Thanks. It is the shell.
