### ISSUE TITLE
Problem with iptables (Android 4.0.4)

### ISSUE THREAD

**Issue by kartataigoo** [skullone/android_firewall#67]
OS: Android 4.0.4 rooted
Android Firewall: v 2.3.4

Firewall doesn't block anything, but all begins good - root permission granted, succesfully accepts config and rules changes, can turn on\off firewall.
When I tried to send bug-report it displayed error message about "ifconfig".

By the way, another firewalls for android didn't work too:
"AFWall+" displays iptables error on switching firewall ON.
"Root Firewall" displays error on applying any rule:

"Error applying iptables rules. Exit code: 2
iptables v1.4.10: can't initialize iptables table 'filter': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded."

It's a problem in OS Android on my device?  Please, explain how can I fix it?

best regards, Kartataigoo.
(sorry for my bad english)

**Comment by skullone** [comment]
Please e-mail me directly at androidfirewall.developer@gmail.com

I have a beta build that fixes the ifconfig error so you can send me an
error report.  That way we can figure out what's going on.

Thanks!

-Jason

**Comment by kartataigoo** [comment]
Problem in my device, not in Android Firewall.
