### ISSUE TITLE
VPN service being blocked 4.4.2/5.0.1: Unless access 'Apps running as root' ticked.

### ISSUE THREAD

**Issue by b1k3rdude** [skullone/android_firewall#88]
Morning

Being chasing down an issue with AF 2.3.5 where VPN dosen't connect,  so I enabled logging and found the following (see attached). I have "1016: VPN networking" allowed through the FW, the only way to get VPN through the FW is to allow "Applications running as root". 
1. why is a system app (how do I narrow down which app/service for VPN it is) running as root. 
2. Enabling access through the FW for "any app running as root" isn't an option.

I am happy to do bug testing of alpha/beta versions as I imagine this is effecting ALL users. I have confirmed the issue on Goldeneye 49.2 (4.4.2) and 53 (5.0.1) roms for the Samsung i9505 int.

kind regards

b.

[screenshot_2015-06-12-10-15-38](https://cloud.githubusercontent.com/assets/12858109/8127207/d6669e9a-10ec-11e5-93d7-b031a430480d.jpg)

**Comment by b1k3rdude** [comment]
Ive tested & confirm this behavior on a friends Note 2 running 4.4.2.

**Comment by b1k3rdude** [comment]
This can be closed as app is no longer being worked on, see - 
- https://github.com/skullone/android_firewall/issues/89

**Comment by Gitoffthelawn** [comment]
@b1k3rdude Do you think it's best to close your issue or leave it open?  SkullOne said he/she has discontinued the app "for the time being".  So development might resume.

Also, since this is open-source, another developer might want to continue development or fork it (license permitting).
